#!/usr/bin/env php
<?php
use Wandu\Foundation\Application;
use Wandu\Foundation\Definitions\NeedInstallDefinition;
use Wandu\Foundation\Kernels\ConsoleKernel;

$autoloadPath = realpath(__DIR__);
while (!file_exists($autoloadPath . '/vendor/autoload.php')) {
    if ($autoloadPath == '/' || !$autoloadPath) {
        echo "cannot find autoload.php. you may run composer install.\n";
        exit(-1);
    }
    $autoloadPath = dirname($autoloadPath);
}

define('WANDU_BASE_PATH', $autoloadPath);
require_once WANDU_BASE_PATH . '/vendor/autoload.php';
unset($autoloadPath);

$appPath = realpath(getcwd());
while (!file_exists($appPath . '/.wandu.php')) {
    if ($appPath == '/' || !$appPath) {
        $appPath = null;
        break;
    }
    $appPath = dirname($appPath);
}

if (isset($appPath)) {
    $definition = require $appPath . '/.wandu.php';
} else {
    $definition = new NeedInstallDefinition();
}
define('WANDU_APP_PATH', $appPath);
unset($appPath);

$app = new Application(new ConsoleKernel($definition));
$app->instance('base_path', WANDU_BASE_PATH);
$app->instance('app_path', WANDU_APP_PATH);
exit($app->execute());
