#!/usr/bin/env php
<?php
use Wandu\Foundation\Application;
use Wandu\Foundation\Definitions\NeedInstallDefinition;
use Wandu\Foundation\Kernels\ConsoleKernel;

$autoloadPath = realpath(__DIR__);
while (!file_exists($autoloadPath . '/vendor/autoload.php')) {
    if ($autoloadPath == '/' || !$autoloadPath) {
        echo "cannot find autoload.php. you may run composer install.\n";
        exit(-1);
    }
    $autoloadPath = dirname($autoloadPath);
}

require_once $autoloadPath . '/vendor/autoload.php';
chdir($autoloadPath);
unset($autoloadPath);

if (file_exists('.wandu.php')) {
    $definition = require '.wandu.php';
} else {
    $definition = new NeedInstallDefinition();
}

$app = new Application(new ConsoleKernel($definition));
exit($app->execute());
